variables:
   IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
   APP_NAME: deusops-may
   NS: ns1

stages:
    - build
    - deploy-manifest
    - deploy-helm
    - deploy-helm-via-package-registry

# сборка и заливка в gitlab container registry
# build:
#     stage: build
#     image: docker:26.1.3
#     services:
#     - docker:dind
#     tags:
#       - docker
#     script:
#       - echo $CI_REGISTRY_USER
#       - echo $CI_REGISTRY_PASSWORD
#       - echo $CI_REGISTRY
#       - echo $IMAGE_TAG
#       - echo "$CA_CERTIFICATE"
#       - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#       - docker build -t $IMAGE_TAG .      
#       - docker push $IMAGE_TAG

# переделано на установку через helm, согласно пункту N7 
# deploy-manifest:
#   stage: deploy-manifest
#   tags:
#   - docker
#   image: 
#     name: bitnami/kubectl:latest
#     entrypoint: ['']
#   script:
#     - kubectl config get-contexts
#     - kubectl config use-context root/project1:a1-kuber
#     - kubectl apply -f deployment.yml

# deploy через локальный helm chart в виде файла
# deploy-helm:
#   stage: deploy-helm
#   tags:
#   - docker
#   image: alpine/helm:3.15.2
#   script:
#     - helm upgrade ${APP_NAME} ./charts --install --values=./charts/values.yaml --namespace ${NS}

deploy-helm-via-package-registry:
  stage: deploy-helm-via-package-registry
  tags:
  - docker
  image: alpine/helm:3.15.2
    entrypoint: [""] 
  script:
    #- echo ${CI_API_V4_URL}
    - helm repo add --username ${CI_JOB_TOKEN} --password ${CI_JOB_TOKEN } project1-helm-charts https://${CI_API_V4_URL}/projects/project1-helm-charts/packages/helm/stable
    - helm install my-release project-1/mychart

