stages:
    - build

stage_build:
    stage: build
    image: ubuntu:22.04
    tags:
        - shared-tag
    script:
        - echo "Privet Gitlab!"
        - cd build
        - touch "somefile.txt"
        - echo "123" >> "somefile.txt"
    artifacts:
        paths:
            - build
        expire_in: 30 days
#        untracked: false
#        when: on_success
#        access: all
#        expire_in: 30 days