variables:
   IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
   APP_NAME: deusops-may
   NS: ns1

stages:
    - build
    - deploy-manifest
    - deploy-helm
    - deploy-helm-via-package-registry

# сборка и заливка в gitlab container registry
# build:
#     stage: build
#     image: docker:26.1.3
#     services:
#     - docker:dind
#     tags:
#       - docker
#     script:
#       - echo $CI_REGISTRY_USER
#       - echo $CI_REGISTRY_PASSWORD
#       - echo $CI_REGISTRY
#       - echo $IMAGE_TAG
#       - echo "$CA_CERTIFICATE"
#       - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#       - docker build -t $IMAGE_TAG .      
#       - docker push $IMAGE_TAG

# переделано на установку через helm, согласно пункту N7 
# deploy через kebernetes manifest
# deploy-manifest:
#   stage: deploy-manifest
#   tags:
#   - docker
#   image: 
#     name: bitnami/kubectl:latest
#     entrypoint: ['']
#   script:
#     - kubectl config get-contexts
#     - kubectl config use-context root/project1:a1-kuber
#     - kubectl apply -f deployment.yml

# deploy через локальный helm chart в виде файла
# deploy-helm:
#   stage: deploy-helm
#   tags:
#   - docker
#   image: alpine/helm:3.15.2
#   script:
#     - helm upgrade ${APP_NAME} ./charts --install --values=./charts/values.yaml --namespace ${NS}

# deploy через gitlab helm package registry из отдельного проекта (H4)
deploy-helm-via-package-registry:
  stage: deploy-helm-via-package-registry
  tags:
  - shell
  # image: 
  #   name: alpine/helm:3.15.2
  #   entrypoint: [''] 
  script:
    - helm repo add --username ${CI_JOB_TOKEN} --password ${CI_JOB_TOKEN} deusops-may ${CI_API_V4_URL}/projects/4/packages/helm/stable
    - helm repo update
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
    #- cat ~/.kube/config
    # - echo $KUBECONFIG
    #- cat /builds/root/project1.tmp/KUBECONFIG
    - helm install my-release deusops-may/deusops-may

##