#variables:
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_TLS_CERTDIR: ""
variables:
   IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
   DOCKER_TLS_CERTDIR: "/certs"
stages:
    - build

stage_build:
    stage: build
    image: docker:26.1.3
    services:
    - docker:dind
    tags:
      - shared-tag
    script:
#      - docker build -t deusops-may-flask-app .
      - echo $CI_REGISTRY_USER
      - echo $CI_REGISTRY_PASSWORD
      - echo $CI_REGISTRY
      - echo $IMAGE_TAG
      - echo "END"
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t $IMAGE_TAG .      
      - docker push $IMAGE_TAG


####