stages:
    - build

stage_build:
    stage: build
    image: ubuntu:22.04
    tags:
        - shared-tag
    script:
        - echo "Privet Gitlab!"
        - mkdir build
        - cd build
        - touch "somefile.txt"
        - echo "123" >> "somefile.txt"
        - echo $MYVAR
        - echo $MYVAR2
    artifacts:
        paths:
            - build
        expire_in: 30 days
#        untracked: false
#        when: on_success
#        access: all
#        expire_in: 30 days
stage_build2:
    stage: build
    tags:
        - shared-tag

    script:
        - echo "Hello from build2!"
    