#variables:
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_TLS_CERTDIR: ""

stages:
    - build

stage_build:
    stage: build
    image: docker:26.1.3
    services:
    - docker:dind
    tags:
      - shared-tag
    script:
      - docker build -t deusops-may-flask-app .
      - echo $CI_REGISTRY_USER
      - echo $CI_REGISTRY_PASSWORD
      - echo $CI_REGISTRY
      - echo "END"


##