---
kind: Namespace
apiVersion: v1
metadata:
  name: ns1
  labels:
    name: deusops-may
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deusops-may
  namespace: ns1  
spec:
  selector:
    matchLabels:
      app: deusops-may
  replicas: 3
  template:
    metadata:
      labels:
        app: mdeusops-may
    spec:
      containers:
      - name: deusops-may
        image: gitlab.r55.dev:5050/root/project1:main
        ports:
        - containerPort: 5000
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: myservice1
  namespace: ns1
spec:
  type: ClusterIP
  selector:
    app: deusops-may
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000